/* eslint-disable */
/* tslint:disable */

// generated by react-imported-component, DO NOT EDIT
import {assignImportedComponents} from 'react-imported-component/macro';

const PreloadComponent = imported(() => import('./PreloadThis'));
const PrefetchChunkComponent = imported(() => import('./ChunkThis'));

const applicationImports = assignImportedComponents([
  [() => import('./should-not-be-transformed'), '', './some-file', false],
]);

