var importedWrapper = require('react-imported-component/wrapper');

import { assignImportedComponents } from "react-imported-component/boot";

/* eslint-disable */

/* tslint:disable */
// generated by react-imported-component, DO NOT EDIT
const PreloadComponent = imported(() => importedWrapper("imported_-hbct7n_component", import('./PreloadThis')));
const PrefetchChunkComponent = imported(() => importedWrapper("imported_fspdct_component", import(
/* webpackChunkName: "chunked-this" */
'./ChunkThis')));
const applicationImports = assignImportedComponents([[() => importedWrapper("imported_12i8gg9_component", import('./should-not-be-transformed')), '', './some-file', false]]);